export const views = {
  HOME: 'HOME',
  DEFAULT: 'HOME',
  QUEUE: 'QUEUE',
  SONGS: 'SONGS',
  ALBUMS: 'ALBUMS',
  ARTISTS: 'ARTISTS',
  FAVORITES: 'FAVORITES',
  RECENTLY_PLAYED: 'RECENTLY_PLAYED',
  SETTINGS: 'SETTINGS',
  USERS: 'USERS',
  YOUTUBE: 'YOUTUBE',
  VISUALIZER: 'VISUALIZER',
  PROFILE: 'PROFILE',
  ALBUM: 'ALBUM',
  ARTIST: 'ARTIST',
  PLAYLIST: 'PLAYLIST'
}
